### PR TITLE
Rename the Cache\Null to Cache\None since it's a reserved keyword in PHP7.

### PR DESCRIPTION
**Pull request by sukei**

### CODE REVIEW

**Comment by rulatir** [comment]
Bump?

**Comment by sukei** [comment]
What do you mean?

**Comment by rulatir** [comment]
Bumping this pull request.

**Comment by sukei** [comment]
Version number?

**Comment by rulatir** [comment]
No, "bumping" as in "trying to get maintainer's attention" :)

**Comment by sukei** [comment]
Okayyy, just like "up"! sorry, it's the first time I see this expression.

**Comment by PommeVerte** [comment]
+1 for this as well.

**Comment by quentinfayet** [comment]
+1

**Comment by nebkam** [comment]
+1

**Comment by andrewnester** [comment]
+1 I guess it can be easily merged, am I right?

**Pull request merged**
